config/routes.rb
Twitter::Application.routes.draw do
  devise_for :users
  resources :tweets , except: [:new, :show]

  get 'following', to: 'home#following'
  get 'follower', to: 'home#follower'
  post 'follow', to: 'home#follow_user'
  delete 'un_follow', to: 'home#un_follow'

  root :to =>'home#index'
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, :class_name => "User", :foreign_key => :follower_id
  belongs_to :following, :class_name => "User", :foreign_key => :following_id
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  has_many :tweets

  has_many :followers, :class_name => "Follow", :foreign_key => :follower_id
  has_many :followings, :class_name => "Follow", :foreign_key => :following_id

  validates_presence_of :username
  validates_uniqueness_of :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # add username to user controller
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:sign_in) do |u|
      u.permit(:username, :password, :remember_me)
    end
  end

  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def follow_user
    following_user = User.find_by username: params[:follow][:username]


    if following_user
      following_msg = 'Already Following the User'
      Follow.find_or_create_by(follower_id: current_user.id, following_id: following_user.id) do |f|
        following_msg = 'Successfully Following the User'
      end
      flash[:notice] = following_msg
      redirect_to following_path
    else
      flash[:notice] = 'User Not Found'
      redirect_to following_path
    end
  end

  def following
    @following = Follow.where(:follower => current_user)
  end

  def un_follow
    Follow.where(:follower => current_user, following_id: params[:id]).destroy_all

    redirect_to following_path
  end

  def follower
    @followers = Follow.where(:following => current_user)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @tweet = Tweet.new(params[:tweet].permit(:body))
    @tweet.user_id = current_user.id

    @tweet.save
    redirect_to tweets_path
  end

  def index
    users_for_tweets = Follow.where(:follower_id => current_user.id).pluck(:following_id)
    users_for_tweets.append(current_user.id)

    @tweets = Tweet.where(user_id: users_for_tweets).order('created_at asc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/home/follower.html.erb
<% if !@followers.empty? %>
    <h3>Followers:- </h3>
    <ul>
        <% @followers.each do |f| %>
            <li>
                <%= f.follower.username %> | <%= f.follower.email %>
            </li>
        <% end %>
    </ul>
<% else %>
    <h3>You have No Followers !</h3>
<% end %>

<%= link_to "Home", root_path, :method => :get %>

app/views/home/following.html.erb
<h3>Follow User :- </h3>
<%= form_for :follow, url: follow_path do |f|%>
    <% if @error %>
        <div id="error_explanation">
            <%= @error %>
        </div>
    <% end %>
    <p>
        <%= f.label :username %><br>
        <%= f.text_field :username %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= notice %>

<% if !@following.empty? %>
    <h3>Following:- </h3>
    <ul>
        <% @following.each do |f| %>
            <li><%= f.following.username %> | <%= f.following.email %>
                <%= button_to "UnFollow User", { action: "un_follow", id: f.following.id },
                              method: :delete, data: { confirm: "Are you sure?" } %>
            </li>
        <% end %>
    </ul>
<% else %>
    <h3>You are not following anyone right now!</h3>
<% end %>

<%= link_to "Home", root_path, :method => :get %>

app/views/home/index.html.erb
<% if user_signed_in? %>

    <h2>Welcome <%= current_user.username %></h2>

    <%= link_to "Tweets", tweets_path, :method => :get %>
    </br>
    <%= link_to "Following Users", following_path, :method => :get %>
    </br>
    <%= link_to "Followers", follower_path, :method => :get %>
    </br>
    <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>

<% else %>

    <h1> welcome to twitter community</h1>
    <%= link_to "Sign In", new_user_session_path, :method => :get %>
    <%= link_to "Sign up", new_user_registration_path, :method => :get %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<h1>Tweets</h1>


<%= form_for :tweet, url: tweets_path do |f| %>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>


<table>
    <tr>
        <th>Sender</th>
        <th>Tweet</th>
        <th>Tweeted At</th>
    </tr>

    <% @tweets.each do |tweet| %>
        <tr>
            <td><%= tweet.user.username if tweet.user %></td>
            <td><%= tweet.body %></td>
            <td><%= tweet.created_at %></td>
        </tr>
    <% end %>
</table>

<%= link_to "Home", root_path, :method => :get %>